### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#1]
Is this an option given the dependencies?

**Comment by danielfrg** [comment]
The only dependency that doesn't work on python 3 is the cloudera manager api [`cm_api`](https://cloudera.github.io/cm_api/) but that is not really needed for a dask.distributed cluster only needed for some future functionality.

**Comment by danielfrg** [comment]
I just saw this error from paramiko: https://github.com/paramiko/paramiko/issues/615 but is already fixed and should be available on a newer release of paramiko.

**Comment by mrocklin** [comment]
Still trying out Python 3 from time to time.  

```
mrocklin@workstation:~$ dec2 up --name mycluster --keyname mrocklin --keypair ~/.ssh/anaconda-cluster.pem
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/bin/dec2", line 9, in <module>
    load_entry_point('dec2==0+untagged.41.g87709a3', 'console_scripts', 'dec2')()
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/setuptools-19.6.2-py3.4.egg/pkg_resources/__init__.py", line 547, in load_entry_point
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/setuptools-19.6.2-py3.4.egg/pkg_resources/__init__.py", line 2719, in load_entry_point
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/setuptools-19.6.2-py3.4.egg/pkg_resources/__init__.py", line 2379, in load
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/setuptools-19.6.2-py3.4.egg/pkg_resources/__init__.py", line 2385, in resolve
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dec2/__init__.py", line 2, in <module>
    from .cluster import Cluster
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dec2/cluster.py", line 3, in <module>
    import urllib2
ImportError: No module named 'urllib2'
```

**Comment by danielfrg** [comment]
There is no urllib2 in python 3? How do you usually solve this?

**Comment by mrocklin** [comment]
Compatibility file
https://github.com/dask/dask/blob/master/dask/compatibility.py

**Comment by danielfrg** [comment]
Should be fixed on https://github.com/dask/dec2/commit/83ee5003843f4960f83672482496631c7aace988

**Comment by danielfrg** [comment]
With https://github.com/dask/dec2/pull/6 and https://github.com/dask/dec2/commit/302f68c1a9c77988ec5f18d4c1eeeb98f8b72fa5 all the issues should be fixed.
