### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER] wrong version number

### ISSUE THREAD

**Issue by runyuzhang** [dask/dask-ec2#102]
Trying to set up dask-ec2 on my cluster, and ran into this issue. Here is the stack trace:

DEBUG: Uploading file /var/folders/t0/98v23y113_73j625cw8nlz340000gn/T/tmpftoc8c to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /srv/pillar/dask.sls' on '54.227.57.135'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.227.57.135'
Installing scheduler
https://54.227.57.135:8000/login
{"username": "saltdev", "password": "saltdev", "eauth": "pam"}
{'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/json', 'Accept': 'application/json'}
https://54.227.57.135:8000/login
Traceback (most recent call last):
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/dask_ec2/cli/main.py", line 23, in start
    cli(obj={})
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/dask_ec2/cli/daskd.py", line 31, in dask
    ctx.invoke(dask_install, filepath=filepath, nprocs=nprocs, source=source)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/dask_ec2/cli/daskd.py", line 72, in dask_install
    cluster.pepper.local("node-0", "grains.append", ["roles", "dask.distributed.scheduler"])
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/dask_ec2/cluster.py", line 55, in get_pepper_client
    self._pepper.login('saltdev', 'saltdev', 'pam')
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/dask_ec2/libpepper.py", line 286, in login
    'eauth': eauth}).get('return', [{}])[0]
  File "/Users/runyuzhang/code/kaggle/kaggle-env/lib/python2.7/site-packages/dask_ec2/libpepper.py", line 134, in req
    f = urlopen(req, context=con)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1752)

Not sure what went wrong, it seems like its not the common issue of making a HTTP request to an HTTPS server because I printed out the url and req header, and it seems like it is making a HTTPS call.

**Comment by fivejjs** [comment]
yes, I got the same issue: 
```
dask-ec2 up --keyname daskec --keypair daskec.pem --region-name ap-southeast-2 --ami ami-e2021d81 --tags dummy:tag
```
passed some salt debug
bug get:
```
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2178)
```
