### ISSUE TITLE
CherryPy Error; JSON Parsing Error from Pepper

### ISSUE THREAD

**Issue by dsidi** [dask/dask-ec2#25]
I'm getting an error about installing CherryPy because pip is not installed when running dask-ec2 with default arguments:

--snip--

```
Bootstraping salt master
DEBUG: Running command sudo -S bash -c 'curl -sS -L https://bootstrap.saltstack.com | sh -s -- -d -X -M -N stable' on '54.209.163.215'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -M -N -P -L -p salt-api stable' on '54.209.163.215'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/templates/auto_accept.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/auto_accept.conf' on '54.209.163.215'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.209.163.215'
DEBUG: Running command sudo -S bash -c 'pip install cherrypy' on '54.209.163.215'
DEBUG: Attempt 1/3 of function '__install_salt_rest_api' failed
DEBUG: Running command sudo -S bash -c 'pip install cherrypy' on '54.209.163.215'
DEBUG: Attempt 2/3 of function '__install_salt_rest_api' failed
DEBUG: Running command sudo -S bash -c 'pip install cherrypy' on '54.209.163.215'
DEBUG: Attempt 3/3 of function '__install_salt_rest_api' failed
ERROR: bash: pip: command not found
Couldn't install CherryPy. Error is above (maybe try again)
```

--snip--

After fixing this with fabric and rerunning, there is an error parsing a server response in JSON:

--snip--

```
Bootstraping salt master
DEBUG: Running command sudo -S bash -c 'curl -sS -L https://bootstrap.saltstack.com | sh -s -- -d -X -M -N stable' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -M -N -P -L -p salt-api stable' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/templates/auto_accept.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/auto_accept.conf' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'pip install cherrypy' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'pip install PyOpenSSL' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'salt-call --local tls.create_self_signed_cert' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/templates/rest_cherrypy.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/rest_cherrypy.conf' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/templates/external_auth.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/external_auth.conf' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'id -u saltdev &>/dev/null || useradd -p $(openssl passwd -1 saltdev) saltdev' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'service salt-master restart' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'service salt-api restart' on '52.90.3.73'
Bootstraping salt minions
DEBUG: Installing salt-minion on all the nodes
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 52.90.3.73 -i node-0 stable' on '52.90.3.73'
DEBUG: Configuring salt-mine on the salt minions
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.90.3.73'
DEBUG: Restarting the salt-minion service
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '52.90.3.73'
Uploading salt formulas
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt to /srv/salt
DEBUG: Running command sudo -S bash -c 'mkdir -p /srv/salt' on '52.90.3.73'
DEBUG: Creating directory /tmp/.__tmp_copy mode=511
DEBUG: Creating directory /tmp/.__tmp_copy/system mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/system to /tmp/.__tmp_copy/system
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/system' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/system/macros.sls to /tmp/.__tmp_copy/system/macros.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/system/base.sls to /tmp/.__tmp_copy/system/base.sls
DEBUG: Creating directory /tmp/.__tmp_copy/system/templates mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/system/templates to /tmp/.__tmp_copy/system/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/system/templates' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/system/templates/limits.conf to /tmp/.__tmp_copy/system/templates/limits.conf
DEBUG: Creating directory /tmp/.__tmp_copy/conda mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/conda to /tmp/.__tmp_copy/conda
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/conda' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/conda/init.sls to /tmp/.__tmp_copy/conda/init.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/conda/settings.sls to /tmp/.__tmp_copy/conda/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/conda/templates mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/conda/templates to /tmp/.__tmp_copy/conda/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/conda/templates' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/conda/templates/conda.sh to /tmp/.__tmp_copy/conda/templates/conda.sh
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/conda/debug.sls to /tmp/.__tmp_copy/conda/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask to /tmp/.__tmp_copy/dask
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask' on '52.90.3.73'
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed to /tmp/.__tmp_copy/dask/distributed
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/init.sls to /tmp/.__tmp_copy/dask/distributed/init.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/scheduler mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/scheduler to /tmp/.__tmp_copy/dask/distributed/scheduler
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/scheduler' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/scheduler/init.sls to /tmp/.__tmp_copy/dask/distributed/scheduler/init.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/settings.sls to /tmp/.__tmp_copy/dask/distributed/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/templates mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/templates to /tmp/.__tmp_copy/dask/distributed/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/templates' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/templates/dworker.conf to /tmp/.__tmp_copy/dask/distributed/templates/dworker.conf
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/templates/dscheduler.conf to /tmp/.__tmp_copy/dask/distributed/templates/dscheduler.conf
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/worker mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/worker to /tmp/.__tmp_copy/dask/distributed/worker
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/worker' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/worker/init.sls to /tmp/.__tmp_copy/dask/distributed/worker/init.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/dask/distributed/debug.sls to /tmp/.__tmp_copy/dask/distributed/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/jupyter to /tmp/.__tmp_copy/jupyter
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/jupyter/init.sls to /tmp/.__tmp_copy/jupyter/init.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/jupyter/settings.sls to /tmp/.__tmp_copy/jupyter/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter/templates mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/jupyter/templates to /tmp/.__tmp_copy/jupyter/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter/templates' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/jupyter/templates/jupyter-notebook.conf to /tmp/.__tmp_copy/jupyter/templates/jupyter-notebook.conf
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter/notebook mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/jupyter/notebook to /tmp/.__tmp_copy/jupyter/notebook
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter/notebook' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/jupyter/notebook/init.sls to /tmp/.__tmp_copy/jupyter/notebook/init.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/top.sls to /tmp/.__tmp_copy/top.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java to /tmp/.__tmp_copy/java
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/init.sls to /tmp/.__tmp_copy/java/init.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/settings.sls to /tmp/.__tmp_copy/java/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java/openjdk mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/openjdk to /tmp/.__tmp_copy/java/openjdk
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java/openjdk' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/openjdk/init.sls to /tmp/.__tmp_copy/java/openjdk/init.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/openjdk/settings.sls to /tmp/.__tmp_copy/java/openjdk/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java/openjdk/templates mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/openjdk/templates to /tmp/.__tmp_copy/java/openjdk/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java/openjdk/templates' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/openjdk/templates/java.sh to /tmp/.__tmp_copy/java/openjdk/templates/java.sh
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/openjdk/env.sls to /tmp/.__tmp_copy/java/openjdk/env.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/java/debug.sls to /tmp/.__tmp_copy/java/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/supervisor mode=511
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/supervisor to /tmp/.__tmp_copy/supervisor
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/supervisor' on '52.90.3.73'
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/supervisor/init.sls to /tmp/.__tmp_copy/supervisor/init.sls
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/salt/supervisor/settings.sls to /tmp/.__tmp_copy/supervisor/settings.sls
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy/* /srv/salt' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.90.3.73'
DEBUG: Uploading directory /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/pillar to /srv/pillar
DEBUG: Running command sudo -S bash -c 'mkdir -p /srv/pillar' on '52.90.3.73'
DEBUG: Creating directory /tmp/.__tmp_copy mode=511
DEBUG: Uploading file /home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/formulas/pillar/top.sls to /tmp/.__tmp_copy/top.sls
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy/* /srv/pillar' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.90.3.73'
Uploading conda settings
DEBUG: Uploading file /tmp/tmpejteBK to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /srv/pillar/conda.sls' on '52.90.3.73'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.90.3.73'
Traceback (most recent call last):
  File "/home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/cli/main.py", line 23, in start
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/cli/main.py", line 299, in provision
    ctx.invoke(anaconda, filepath=filepath)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/cli/main.py", line 319, in anaconda
    output = cluster.salt_call("*", "state.sls", ["conda"])
  File "/home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/cluster.py", line 65, in salt_call
    return self.pepper.local(target, module, args)
  File "/home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/cluster.py", line 54, in get_pepper_client
    self._pepper.login('saltdev', 'saltdev', 'pam')
  File "/home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/libpepper.py", line 284, in login
    'eauth': eauth
  File "/home/FOOBAR/.local/lib/python2.7/site-packages/dask_ec2/libpepper.py", line 151, in req
    raise PepperException('Unable to parse the server response.')
PepperException: Unable to parse the server response.
```

--snip--

**Comment by dsidi** [comment]
These problems arose from using an ami without Python 2.7.10: turns out the ssl module in 2.7.6 does not have SSLContext in it (causing the second error mentioned above), and pip is not packaged with python 2.7.6. I had this problem with the default instance, though, so I think it's still a bug.

**Comment by DrHolgerLange** [comment]
I use AWS in EU (Ireland) trying to use Ubuntu 16.04 LTS - Xenial (HVM) AMI from the AWS marketplace and encounter similar problems (python, pip, ssl context). How do I need to setup the AMI to make dask-ec2 work?

**Comment by DrHolgerLange** [comment]
Using the latest git release (git clone https://github.com/dask/dask-ec2.git) on 9/14/2016, the python and pip issues are resolved! Thanks a lot!

I still encounter a **SSLError: {SSL: WRONG_VERSION_NUMBER]** while "**Uploading conda settings**", see below ...

```
Uploading conda settings
DEBUG: Uploading file /tmp/tmp12K_2M to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /srv/pillar/conda.sls' on '52.211.60.114'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.211.60.114'
Traceback (most recent call last):
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cli/main.py", line 23, in start
    cli(obj={})
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cli/main.py", line 165, in up
    ctx.invoke(provision, filepath=filepath, anaconda_=anaconda_, dask=dask, notebook=notebook, nprocs=nprocs)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cli/main.py", line 306, in provision
    ctx.invoke(anaconda, filepath=filepath)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cli/main.py", line 326, in anaconda
    output = cluster.salt_call("*", "state.sls", ["conda"])
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cluster.py", line 65, in salt_call
    return self.pepper.local(target, module, args)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cluster.py", line 54, in get_pepper_client
    self._pepper.login('saltdev', 'saltdev', 'pam')
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/libpepper.py", line 284, in login
    'eauth': eauth
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/libpepper.py", line 133, in req
    f = urlopen(req, context=con)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1754)
```

**Comment by danielfrg** [comment]
The pip issues should been fixed by now on master. I am going to close this issue so I can to keep track of the server bug on https://github.com/dask/dask-ec2/issues/32
