### ISSUE TITLE
dask_ec2.libpepper.PepperException: Server error

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#30]
```
mrocklin@workstation:~/workspace/dask-ec2$ dask-ec2 provision
Checking SSH connection to nodes
DEBUG: Checking ssh connection for 54.173.16.97
DEBUG: Running command bash -c 'ls' on '54.173.16.97'
DEBUG: Checking ssh connection for 54.173.87.57
DEBUG: Running command bash -c 'ls' on '54.173.87.57'
DEBUG: Checking ssh connection for 54.167.183.231
DEBUG: Running command bash -c 'ls' on '54.167.183.231'
DEBUG: Checking ssh connection for 52.91.178.109
DEBUG: Running command bash -c 'ls' on '52.91.178.109'
DEBUG: Checking ssh connection for 54.173.112.197
DEBUG: Running command bash -c 'ls' on '54.173.112.197'
DEBUG: Checking ssh connection for 54.167.185.99
DEBUG: Running command bash -c 'ls' on '54.167.185.99'
DEBUG: Checking ssh connection for 54.165.69.199
DEBUG: Running command bash -c 'ls' on '54.165.69.199'
DEBUG: Checking ssh connection for 54.82.177.20
DEBUG: Running command bash -c 'ls' on '54.82.177.20'
+-------------------+-----------+
| Node IP           | SSH check |
+===================+===========+
| 54.173.87.57:22   | True      |
| 54.167.183.231:22 | True      |
| 52.91.178.109:22  | True      |
| 54.173.112.197:22 | True      |
| 54.82.177.20:22   | True      |
| 54.165.69.199:22  | True      |
| 54.173.16.97:22   | True      |
| 54.167.185.99:22  | True      |
+-------------------+-----------+
Bootstraping salt master
DEBUG: Running command sudo -S bash -c 'curl -sS -L https://bootstrap.saltstack.com | sh -s -- -d -X -M -N stable' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -M -N -P -L -p salt-api stable' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/auto_accept.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/auto_accept.conf' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'apt-get install -y python-pip' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'pip install cherrypy' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'pip install PyOpenSSL' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'salt-call --local tls.create_self_signed_cert' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/rest_cherrypy.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/rest_cherrypy.conf' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/external_auth.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/external_auth.conf' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'id -u saltdev &>/dev/null || useradd -p $(openssl passwd -1 saltdev) saltdev' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'service salt-master restart' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'service salt-api restart' on '54.173.16.97'
Bootstraping salt minions
DEBUG: Installing salt-minion on all the nodes
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.173.16.97 -i node-2 stable' on '54.167.183.231'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.173.16.97 -i node-7 stable' on '54.82.177.20'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.173.16.97 -i node-0 stable' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.173.16.97 -i node-1 stable' on '54.173.87.57'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.173.16.97 -i node-3 stable' on '52.91.178.109'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.173.16.97 -i node-6 stable' on '54.165.69.199'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.173.16.97 -i node-4 stable' on '54.173.112.197'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.173.16.97 -i node-5 stable' on '54.167.185.99'
DEBUG: Configuring salt-mine on the salt minions
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.167.183.231'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.173.112.197'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.173.87.57'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.167.185.99'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.82.177.20'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.165.69.199'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '52.91.178.109'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.167.183.231'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.82.177.20'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.112.197'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.87.57'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.167.185.99'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.165.69.199'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.91.178.109'
DEBUG: Restarting the salt-minion service
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.167.183.231'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '52.91.178.109'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.173.87.57'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.165.69.199'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.82.177.20'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.173.112.197'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.167.185.99'
Uploading salt formulas
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt to /srv/salt
DEBUG: Running command sudo -S bash -c 'mkdir -p /srv/salt' on '54.173.16.97'
DEBUG: Creating directory /tmp/.__tmp_copy mode=511
DEBUG: Creating directory /tmp/.__tmp_copy/system mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/system to /tmp/.__tmp_copy/system
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/system' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/system/base.sls to /tmp/.__tmp_copy/system/base.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/system/macros.sls to /tmp/.__tmp_copy/system/macros.sls
DEBUG: Creating directory /tmp/.__tmp_copy/system/templates mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/system/templates to /tmp/.__tmp_copy/system/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/system/templates' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/system/templates/limits.conf to /tmp/.__tmp_copy/system/templates/limits.conf
DEBUG: Creating directory /tmp/.__tmp_copy/conda mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/conda to /tmp/.__tmp_copy/conda
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/conda' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/conda/init.sls to /tmp/.__tmp_copy/conda/init.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/conda/debug.sls to /tmp/.__tmp_copy/conda/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/conda/templates mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/conda/templates to /tmp/.__tmp_copy/conda/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/conda/templates' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/conda/templates/conda.sh to /tmp/.__tmp_copy/conda/templates/conda.sh
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/conda/settings.sls to /tmp/.__tmp_copy/conda/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java to /tmp/.__tmp_copy/java
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/init.sls to /tmp/.__tmp_copy/java/init.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/debug.sls to /tmp/.__tmp_copy/java/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java/openjdk mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/openjdk to /tmp/.__tmp_copy/java/openjdk
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java/openjdk' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/openjdk/env.sls to /tmp/.__tmp_copy/java/openjdk/env.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/openjdk/init.sls to /tmp/.__tmp_copy/java/openjdk/init.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java/openjdk/templates mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/openjdk/templates to /tmp/.__tmp_copy/java/openjdk/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java/openjdk/templates' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/openjdk/templates/java.sh to /tmp/.__tmp_copy/java/openjdk/templates/java.sh
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/openjdk/settings.sls to /tmp/.__tmp_copy/java/openjdk/settings.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/java/settings.sls to /tmp/.__tmp_copy/java/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/supervisor mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/supervisor to /tmp/.__tmp_copy/supervisor
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/supervisor' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/supervisor/init.sls to /tmp/.__tmp_copy/supervisor/init.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/supervisor/settings.sls to /tmp/.__tmp_copy/supervisor/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/jupyter to /tmp/.__tmp_copy/jupyter
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/jupyter/init.sls to /tmp/.__tmp_copy/jupyter/init.sls
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter/templates mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/jupyter/templates to /tmp/.__tmp_copy/jupyter/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter/templates' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/jupyter/templates/jupyter-notebook.conf to /tmp/.__tmp_copy/jupyter/templates/jupyter-notebook.conf
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter/notebook mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/jupyter/notebook to /tmp/.__tmp_copy/jupyter/notebook
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter/notebook' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/jupyter/notebook/init.sls to /tmp/.__tmp_copy/jupyter/notebook/init.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/jupyter/settings.sls to /tmp/.__tmp_copy/jupyter/settings.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/top.sls to /tmp/.__tmp_copy/top.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask to /tmp/.__tmp_copy/dask
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask' on '54.173.16.97'
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed to /tmp/.__tmp_copy/dask/distributed
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/init.sls to /tmp/.__tmp_copy/dask/distributed/init.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/debug.sls to /tmp/.__tmp_copy/dask/distributed/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/templates mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/templates to /tmp/.__tmp_copy/dask/distributed/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/templates' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/templates/dscheduler.conf to /tmp/.__tmp_copy/dask/distributed/templates/dscheduler.conf
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/templates/dworker.conf to /tmp/.__tmp_copy/dask/distributed/templates/dworker.conf
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/worker mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/worker to /tmp/.__tmp_copy/dask/distributed/worker
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/worker' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/worker/init.sls to /tmp/.__tmp_copy/dask/distributed/worker/init.sls
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/settings.sls to /tmp/.__tmp_copy/dask/distributed/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/scheduler mode=511
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/scheduler to /tmp/.__tmp_copy/dask/distributed/scheduler
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/scheduler' on '54.173.16.97'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/salt/dask/distributed/scheduler/init.sls to /tmp/.__tmp_copy/dask/distributed/scheduler/init.sls
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy/* /srv/salt' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.16.97'
DEBUG: Uploading directory /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/pillar to /srv/pillar
DEBUG: Running command sudo -S bash -c 'mkdir -p /srv/pillar' on '54.173.16.97'
DEBUG: Creating directory /tmp/.__tmp_copy mode=511
DEBUG: Uploading file /home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/formulas/pillar/top.sls to /tmp/.__tmp_copy/top.sls
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy/* /srv/pillar' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.16.97'
Uploading conda settings
DEBUG: Uploading file /tmp/tmpeais13mn to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /srv/pillar/conda.sls' on '54.173.16.97'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.173.16.97'
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/libpepper.py", line 133, in req
    f = urlopen(req, context=con)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/cli/main.py", line 23, in start
    cli(obj={})
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/cli/main.py", line 306, in provision
    ctx.invoke(anaconda, filepath=filepath)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/cli/main.py", line 326, in anaconda
    output = cluster.salt_call("*", "state.sls", ["conda"])
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/cluster.py", line 65, in salt_call
    return self.pepper.local(target, module, args)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/libpepper.py", line 226, in local
    return self.low([low], path='/')
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/libpepper.py", line 201, in low
    return self.req(path, lowstate)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask_ec2-0.3.0+6.g95eb53a-py3.4.egg/dask_ec2/libpepper.py", line 145, in req
    raise PepperException('Server error.')
dask_ec2.libpepper.PepperException: Server error.
```

**Comment by danielfrg** [comment]
I haven't been able to reproduce this. I just fixed another bug on master but I am pretty sure its unrelated to this and I see other people having a similar error. Could you try again?

**Comment by danielfrg** [comment]
Ok, I just noticed that this happens only in Python 2
