### ISSUE TITLE
"plain vanilla" Installation and Usage fails

### ISSUE THREAD

**Issue by DrHolgerLange** [dask/dask-ec2#32]
**Install Anaconda**

```
Firefox: https://www.continuum.io/downloads
Firefox: Click "PYTHON 2.7" "LINUX 64-BIT"
$: bash ~/Downloads/Anaconda2-4.1.1-Linux-x86_64.sh
$: conda update conda
$: conda update anaconda
$: conda config --add channels conda-forge
```

**Create Conda Environment**

```
$: conda create --name CT python=2
$: source activate CT
```

**Install dask-ec2**

```
$: conda install dask-ec2
```

**Use dask-ec2**

```
$: dask-ec2 up --keyname DaskDistributed --keypair ~/data/Safe/DaskDistributed.pem
```

_Leads to the already documented issue:
CherryPy Error; JSON Parsing Error from Pepper #25_

**Install latest dask-ec2 version from GitHub (9/15/2016)**

```
$: cd ~/sw
$: git clone https://github.com/dask/dask-ec2.git
$: cd dask-ec2
$: python setup.py install
$: cd ~
```

**List conda packages**

```
$: conda list
boto3                     1.3.1                    py27_0  
botocore                  1.4.49                   py27_0    conda-forge
ca-certificates           2016.8.31                     0    conda-forge
certifi                   2016.8.31                py27_0    conda-forge
click                     6.6                      py27_0    conda-forge
docutils                  0.12                     py27_0    conda-forge
futures                   3.0.5                    py27_0    conda-forge
jmespath                  0.9.0                    py27_0    conda-forge
ncurses                   5.9                           9    conda-forge
openssl                   1.0.2h                        2    conda-forge
paramiko                  1.17.2                   py27_0    conda-forge
pip                       8.1.2                    py27_0    conda-forge
pycrypto                  2.6.1                    py27_0    conda-forge
python                    2.7.12                        1    conda-forge
python-dateutil           2.5.3                    py27_0    conda-forge
pyyaml                    3.11                     py27_0    conda-forge
readline                  6.2                           0    conda-forge
setuptools                26.1.1                   py27_0    conda-forge
six                       1.10.0                   py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
dask-ec2                  0.3.0+6.g95eb53a           <pip>
ecdsa                     0.13                     py27_0  
```

**Use dask-ec2**

```
$: dask-ec2 up --keyname DaskDistributed --keypair ~/data/Safe/DaskDistributed.pem
```

**_Lead to PepperException failure ..._**

```
_Uploading conda settings
DEBUG: Uploading file /tmp/tmp_8AnN_ to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /srv/pillar/conda.sls' on '52.3.243.195'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.3.243.195'
Traceback (most recent call last):
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cli/main.py", line 23, in start
    cli(obj={})
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cli/main.py", line 165, in up
    ctx.invoke(provision, filepath=filepath, anaconda_=anaconda_, dask=dask, notebook=notebook, nprocs=nprocs)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cli/main.py", line 306, in provision
    ctx.invoke(anaconda, filepath=filepath)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cli/main.py", line 326, in anaconda
    output = cluster.salt_call("*", "state.sls", ["conda"])
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/cluster.py", line 65, in salt_call
    return self.pepper.local(target, module, args)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/libpepper.py", line 226, in local
    return self.low([low], path='/')
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/libpepper.py", line 201, in low
    return self.req(path, lowstate)
  File "/home/drh/sw/anaconda2/envs/CT/lib/python2.7/site-packages/dask_ec2-0.3.0+6.g95eb53a-py2.7.egg/dask_ec2/libpepper.py", line 145, in req
    raise PepperException('Server error.')
PepperException: Server error._
```

**Comment by danielfrg** [comment]
I just found out that this currently broken in Python 2 if you create a conda env with python3 and install from master it should work. I'll work on a fix soon.

**Comment by DrHolgerLange** [comment]
You are right, I tested Python 3 and it works just fine with the github master git clone https://github.com/dask/dask-ec2.git!

**Comment by DrHolgerLange** [comment]
Using dask-ec2 with **python 3** from Germany with the community AMI for Ubuntu 16.04: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160610 - **ami-0ae77879** on **EU-WEST-1 (Ireland)** creates some **time out** problems for me. 

`dask-ec2 up --region-name eu-west-1 --ami ami-0ae77879 --keyname DaskDistributed --keypair ~/data/Safe/DaskDistributed.pem --security-group DaskDistributed`

Most of the times I get stuck checking the ssh connection:
_DEBUG: Checking ssh connection for 52.211.109.74
DEBUG: Attempt 10/10 of function 'check_ssh' failed
ERROR: Retries limit exceeded_

But even when I get past it, I always get stuck here:
_DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '52.50.33.117'
Error with request: <urlopen error [Errno 110] Connection timed out>
ERROR: Could not connect to salt server. Try `dask-ec2 provision` and try again_

**Comment by quasiben** [comment]
I think there's been a lot of changes since this was filed.  I'm going to close for now and if you are still experiencing trouble please re-open

**Comment by mccarthyryanc** [comment]
I am currently experiencing this problem:

```
dask-ec2 up --ami ami-XXXXXXXX \
            --keyname keyname \
            --keypair keypair.pem \
            --name dasknode \
            --tags Name:dasknode \
            --count 2 \
            --region-name us-west-2 \
            --security-group-id sg-XXXXXXXX \
            --iaminstance-name profile_name \
            --subnet-id subnet-XXXXXXXX 
```

```
Error with request: <urlopen error [Errno -2] Name or service not known>
ERROR: Could not connect to salt server. Try `dask-ec2 provision` and try again
```

Continue to get the same error after running: `dask-ec2 provision`.

dask-ec2, version 0.5.0+5.g1849efc
Python 3.5.4
