### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by raymondchua** [dask/dask-ec2#38]
Hi,
While my dask-ec2 is trying to install the scheduler, I have faced this error message:

Installing scheduler
Traceback (most recent call last):
  File "/home/adas/.local/lib/python2.7/site-packages/dask_ec2/cli/main.py", line 23, in start
    cli(obj={})
  File "/home/adas/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/adas/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/adas/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adas/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adas/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adas/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adas/.local/lib/python2.7/site-packages/dask_ec2/cli/main.py", line 165, in up
    ctx.invoke(provision, filepath=filepath, anaconda_=anaconda_, dask=dask, notebook=notebook, nprocs=nprocs)
  File "/home/adas/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adas/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adas/.local/lib/python2.7/site-packages/dask_ec2/cli/main.py", line 309, in provision
    ctx.invoke(dask_install, filepath=filepath, nprocs=nprocs)
  File "/home/adas/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adas/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adas/.local/lib/python2.7/site-packages/dask_ec2/cli/daskd.py", line 59, in dask_install
    cluster.pepper.local("node-0", "grains.append", ["roles", "dask.distributed.scheduler"])
  File "/home/adas/.local/lib/python2.7/site-packages/dask_ec2/cluster.py", line 54, in get_pepper_client
    self._pepper.login('saltdev', 'saltdev', 'pam')
  File "/home/adas/.local/lib/python2.7/site-packages/dask_ec2/libpepper.py", line 284, in login
    'eauth': eauth
  File "/home/adas/.local/lib/python2.7/site-packages/dask_ec2/libpepper.py", line 133, in req
    f = urlopen(req, context=con)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1754)

**Comment by raymondchua** [comment]
Switched to Ubuntu 14 instead of Ubuntu 16 solved the issue.

**Comment by lionfish0** [comment]
I also have this problem... I'm guessing it's because in more recent versions of ssl, older protocols are disabled by default, maybe?
