### ISSUE TITLE
Could not connect to 127.0.0.1:8786

### ISSUE THREAD

**Issue by raymondchua** [dask/dask-ec2#43]
It seems that 'c = Client('127.0.0.1:8786')  # Connect to scheduler running on the head node' does not work. I will get an error:  OSError: Could not connect to 127.0.0.1:8786

However, if I execute 'c = Client' and then execute c again, it seems to work and shows the following:
<Client: scheduler="127.0.0.1:8786" processes=8 cores=8>

Am I missing something?

**Comment by mrocklin** [comment]
```python
c = Client
c()
```

Is equivalent to

```python
c = Client()
```

Which sets up a "cluster" just on your local machine.

Can you post the logs of your original dask-ec2 call?  I suspect that something went wrong when setting up dask-scheduler.

**Comment by raymondchua** [comment]
@mrocklin , thanks for your prompt reply. Here it is:

```
DEBUG: Searching for default VPC
DEBUG: Default VPC found - Using VPC ID: vpc-93905cf4
DEBUG: Searching for default subnet in VPC vpc-93905cf4
DEBUG: Default subnet found - Using Subnet ID: subnet-143c1d62
Launching nodes
DEBUG: Checking that keyname 'raymond_NV' exists on EC2
DEBUG: Checking that security group 'dask-ec2-default' exists on EC2
DEBUG: Getting all security groups and filtering by VPC ID vpc-93905cf4 and name dask-ec2-default
DEBUG: Found Security groups: [ec2.SecurityGroup(id='sg-1cac9e61')]
DEBUG: Getting all security groups and filtering by VPC ID vpc-93905cf4 and name dask-ec2-default
DEBUG: Found Security groups: [ec2.SecurityGroup(id='sg-1cac9e61')]
DEBUG: Creating 4 instances on EC2
DEBUG: Tagging instance 'i-0181a3acaed7af791'
DEBUG: Tagging instance 'i-0993b8b0e19cfcdb8'
DEBUG: Tagging instance 'i-0b74abb2ec02dcdf7'
DEBUG: Tagging instance 'i-0658192bf18ef1cb4'
Checking SSH connection to nodes
DEBUG: Checking ssh connection for 54.174.78.101
DEBUG: Attempt 1/10 of function 'check_ssh' failed
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/home/adas/.local/lib/python3.5/site-packages/paramiko/transport.py", line 1888, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/adas/.local/lib/python3.5/site-packages/paramiko/packet.py", line 331, in readline
    buf += self._read_timeout(timeout)
  File "/home/adas/.local/lib/python3.5/site-packages/paramiko/packet.py", line 501, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adas/.local/lib/python3.5/site-packages/paramiko/transport.py", line 1744, in run
    self._check_banner()
  File "/home/adas/.local/lib/python3.5/site-packages/paramiko/transport.py", line 1892, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

DEBUG: Checking ssh connection for 54.174.78.101
DEBUG: Running command bash -c 'ls' on '54.174.78.101'
DEBUG: Checking ssh connection for 107.21.168.128
DEBUG: Running command bash -c 'ls' on '107.21.168.128'
DEBUG: Checking ssh connection for 107.21.130.188
DEBUG: Running command bash -c 'ls' on '107.21.130.188'
DEBUG: Checking ssh connection for 54.209.187.134
DEBUG: Running command bash -c 'ls' on '54.209.187.134'
+-------------------+-----------+
| Node IP           | SSH check |
+===================+===========+
| 107.21.130.188:22 | True      |
| 54.174.78.101:22  | True      |
| 54.209.187.134:22 | True      |
| 107.21.168.128:22 | True      |
+-------------------+-----------+
Bootstraping salt master
DEBUG: Running command sudo -S bash -c 'curl -sS -L https://bootstrap.saltstack.com | sh -s -- -d -X -M -N stable' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -M -N -P -L -p salt-api stable' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/templates/auto_accept.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/auto_accept.conf' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'apt-get install -y python-pip' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'pip install cherrypy' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'pip install PyOpenSSL' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'salt-call --local tls.create_self_signed_cert' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/templates/rest_cherrypy.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/rest_cherrypy.conf' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/templates/external_auth.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/master.d/external_auth.conf' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'id -u saltdev &>/dev/null || useradd -p $(openssl passwd -1 saltdev) saltdev' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'service salt-master restart' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'service salt-api restart' on '54.174.78.101'
Bootstraping salt minions
DEBUG: Installing salt-minion on all the nodes
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.174.78.101 -i node-3 stable' on '54.209.187.134'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.174.78.101 -i node-2 stable' on '107.21.130.188'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.174.78.101 -i node-0 stable' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -d -X -P -L -A 54.174.78.101 -i node-1 stable' on '107.21.168.128'
DEBUG: Configuring salt-mine on the salt minions
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/templates/mine_functions.conf to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '107.21.168.128'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '107.21.130.188'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /etc/salt/minion.d/mine.conf' on '54.209.187.134'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '107.21.168.128'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '107.21.130.188'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.209.187.134'
DEBUG: Restarting the salt-minion service
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '107.21.130.188'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '54.209.187.134'
DEBUG: Running command sudo -S bash -c 'service salt-minion restart' on '107.21.168.128'
Uploading salt formulas
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt to /srv/salt
DEBUG: Running command sudo -S bash -c 'mkdir -p /srv/salt' on '54.174.78.101'
DEBUG: Creating directory /tmp/.__tmp_copy mode=511
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/top.sls to /tmp/.__tmp_copy/top.sls
DEBUG: Creating directory /tmp/.__tmp_copy/conda mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/conda to /tmp/.__tmp_copy/conda
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/conda' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/conda/init.sls to /tmp/.__tmp_copy/conda/init.sls
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/conda/settings.sls to /tmp/.__tmp_copy/conda/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/conda/templates mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/conda/templates to /tmp/.__tmp_copy/conda/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/conda/templates' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/conda/templates/conda.sh to /tmp/.__tmp_copy/conda/templates/conda.sh
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/conda/debug.sls to /tmp/.__tmp_copy/conda/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java to /tmp/.__tmp_copy/java
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/init.sls to /tmp/.__tmp_copy/java/init.sls
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/settings.sls to /tmp/.__tmp_copy/java/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java/openjdk mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/openjdk to /tmp/.__tmp_copy/java/openjdk
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java/openjdk' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/openjdk/init.sls to /tmp/.__tmp_copy/java/openjdk/init.sls
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/openjdk/settings.sls to /tmp/.__tmp_copy/java/openjdk/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/java/openjdk/templates mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/openjdk/templates to /tmp/.__tmp_copy/java/openjdk/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/java/openjdk/templates' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/openjdk/templates/java.sh to /tmp/.__tmp_copy/java/openjdk/templates/java.sh
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/openjdk/env.sls to /tmp/.__tmp_copy/java/openjdk/env.sls
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/java/debug.sls to /tmp/.__tmp_copy/java/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/supervisor mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/supervisor to /tmp/.__tmp_copy/supervisor
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/supervisor' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/supervisor/init.sls to /tmp/.__tmp_copy/supervisor/init.sls
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/supervisor/settings.sls to /tmp/.__tmp_copy/supervisor/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask to /tmp/.__tmp_copy/dask
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask' on '54.174.78.101'
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed to /tmp/.__tmp_copy/dask/distributed
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/init.sls to /tmp/.__tmp_copy/dask/distributed/init.sls
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/settings.sls to /tmp/.__tmp_copy/dask/distributed/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/templates mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/templates to /tmp/.__tmp_copy/dask/distributed/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/templates' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/templates/dscheduler.conf to /tmp/.__tmp_copy/dask/distributed/templates/dscheduler.conf
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/templates/dworker.conf to /tmp/.__tmp_copy/dask/distributed/templates/dworker.conf
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/worker mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/worker to /tmp/.__tmp_copy/dask/distributed/worker
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/worker' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/worker/init.sls to /tmp/.__tmp_copy/dask/distributed/worker/init.sls
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/debug.sls to /tmp/.__tmp_copy/dask/distributed/debug.sls
DEBUG: Creating directory /tmp/.__tmp_copy/dask/distributed/scheduler mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/scheduler to /tmp/.__tmp_copy/dask/distributed/scheduler
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/dask/distributed/scheduler' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/dask/distributed/scheduler/init.sls to /tmp/.__tmp_copy/dask/distributed/scheduler/init.sls
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/jupyter to /tmp/.__tmp_copy/jupyter
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/jupyter/init.sls to /tmp/.__tmp_copy/jupyter/init.sls
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/jupyter/settings.sls to /tmp/.__tmp_copy/jupyter/settings.sls
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter/templates mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/jupyter/templates to /tmp/.__tmp_copy/jupyter/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter/templates' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/jupyter/templates/jupyter-notebook.conf to /tmp/.__tmp_copy/jupyter/templates/jupyter-notebook.conf
DEBUG: Creating directory /tmp/.__tmp_copy/jupyter/notebook mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/jupyter/notebook to /tmp/.__tmp_copy/jupyter/notebook
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/jupyter/notebook' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/jupyter/notebook/init.sls to /tmp/.__tmp_copy/jupyter/notebook/init.sls
DEBUG: Creating directory /tmp/.__tmp_copy/system mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/system to /tmp/.__tmp_copy/system
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/system' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/system/base.sls to /tmp/.__tmp_copy/system/base.sls
DEBUG: Creating directory /tmp/.__tmp_copy/system/templates mode=511
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/system/templates to /tmp/.__tmp_copy/system/templates
DEBUG: Running command sudo -S bash -c 'mkdir -p /tmp/.__tmp_copy/system/templates' on '54.174.78.101'
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/system/templates/limits.conf to /tmp/.__tmp_copy/system/templates/limits.conf
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/salt/system/macros.sls to /tmp/.__tmp_copy/system/macros.sls
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy/* /srv/salt' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.174.78.101'
DEBUG: Uploading directory /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/pillar to /srv/pillar
DEBUG: Running command sudo -S bash -c 'mkdir -p /srv/pillar' on '54.174.78.101'
DEBUG: Creating directory /tmp/.__tmp_copy mode=511
DEBUG: Uploading file /home/adas/.local/lib/python3.5/site-packages/dask_ec2/formulas/pillar/top.sls to /tmp/.__tmp_copy/top.sls
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy/* /srv/pillar' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.174.78.101'
Uploading conda settings
DEBUG: Uploading file /tmp/tmp5fdnj8h8 to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /srv/pillar/conda.sls' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.174.78.101'
+---------+----------------------+-----------------+
| Node ID | # Successful actions | # Failed action |
+=========+======================+=================+
| node-0  | 6                    | 0               |
| node-1  | 6                    | 0               |
| node-2  | 6                    | 0               |
| node-3  | 6                    | 0               |
+---------+----------------------+-----------------+
DEBUG: Uploading file /tmp/tmpl733f1he to /tmp/.__tmp_copy
DEBUG: Running command sudo -S bash -c 'cp -rf /tmp/.__tmp_copy /srv/pillar/dask.sls' on '54.174.78.101'
DEBUG: Running command sudo -S bash -c 'rm -rf /tmp/.__tmp_copy' on '54.174.78.101'
Installing scheduler
+---------+----------------------+-----------------+
| Node ID | # Successful actions | # Failed action |
+=========+======================+=================+
| node-0  | 18                   | 0               |
+---------+----------------------+-----------------+
Installing workers
+---------+----------------------+-----------------+
| Node ID | # Successful actions | # Failed action |
+=========+======================+=================+
| node-1  | 18                   | 0               |
| node-2  | 18                   | 0               |
| node-3  | 18                   | 0               |
+---------+----------------------+-----------------+
Dask.Distributed Installation succeeded
```

**Comment by quasiben** [comment]
This should be resolved with latest master

**Comment by raymondchua** [comment]
Works now with the latest master. Thanks!
