### ISSUE TITLE
Exception when printing state of empty Salt output 

### ISSUE THREAD

**Issue by jbcrail** [dask/dask-ec2#79]
When a Salt command returns a dictionary like `{u'return': [{}]}`, the `print_state` method converts this to a `None` response, causing the following error:

```
Installing scheduler
Traceback (most recent call last):
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/dask_ec2-0.4.0+12.g8492341.dirty-py2.7.egg/dask_ec2/cli/main.py", line 26, in start
    cli(obj={})
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/dask_ec2-0.4.0+12.g8492341.dirty-py2.7.egg/dask_ec2/cli/main.py", line 368, in provision
    ctx.invoke(dask_install, filepath=filepath, nprocs=nprocs, source=source)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/dask_ec2-0.4.0+12.g8492341.dirty-py2.7.egg/dask_ec2/cli/daskd.py", line 74, in dask_install
    response = print_state(output)
  File "/Users/jcrail/anaconda2/envs/ec2/lib/python2.7/site-packages/dask_ec2-0.4.0+12.g8492341.dirty-py2.7.egg/dask_ec2/cli/main.py", line 399, in print_state
    data.extend(response.aggregated_to_table(agg=len))
AttributeError: 'NoneType' object has no attribute 'aggregated_to_table'
```

**Comment by LongBeach805** [comment]
Any headway on this? This is where I am stuck at.
